apiVersion: v1
kind: Service
metadata:
  name: kubewatch
  namespace: sample-app-namespace-1745645327867
  labels:
    app.kubernetes.io/name: kubewatch
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kubewatch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80